// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.221104.6

#pragma once
#ifndef WINRT_WcsNativeWinUI_0_H
#define WINRT_WcsNativeWinUI_0_H
WINRT_EXPORT namespace winrt::Microsoft::UI::Xaml::Markup
{
    struct IXamlMetadataProvider;
}
WINRT_EXPORT namespace winrt::WcsNativeWinUI
{
    struct IMainPage;
    struct IMainWindow;
    struct MainPage;
    struct MainWindow;
    struct XamlMetaDataProvider;
}
namespace winrt::impl
{
    template <> struct category<winrt::WcsNativeWinUI::IMainPage>{ using type = interface_category; };
    template <> struct category<winrt::WcsNativeWinUI::IMainWindow>{ using type = interface_category; };
    template <> struct category<winrt::WcsNativeWinUI::MainPage>{ using type = class_category; };
    template <> struct category<winrt::WcsNativeWinUI::MainWindow>{ using type = class_category; };
    template <> struct category<winrt::WcsNativeWinUI::XamlMetaDataProvider>{ using type = class_category; };
    template <> inline constexpr auto& name_v<winrt::WcsNativeWinUI::MainPage> = L"WcsNativeWinUI.MainPage";
    template <> inline constexpr auto& name_v<winrt::WcsNativeWinUI::MainWindow> = L"WcsNativeWinUI.MainWindow";
    template <> inline constexpr auto& name_v<winrt::WcsNativeWinUI::XamlMetaDataProvider> = L"WcsNativeWinUI.XamlMetaDataProvider";
    template <> inline constexpr auto& name_v<winrt::WcsNativeWinUI::IMainPage> = L"WcsNativeWinUI.IMainPage";
    template <> inline constexpr auto& name_v<winrt::WcsNativeWinUI::IMainWindow> = L"WcsNativeWinUI.IMainWindow";
    template <> inline constexpr guid guid_v<winrt::WcsNativeWinUI::IMainPage>{ 0x3956AC09,0x4D01,0x566E,{ 0xB2,0x22,0x4E,0x95,0x8B,0xFE,0x30,0xF8 } }; // 3956AC09-4D01-566E-B222-4E958BFE30F8
    template <> inline constexpr guid guid_v<winrt::WcsNativeWinUI::IMainWindow>{ 0x9C7EF99E,0x8AEE,0x5C0D,{ 0x93,0x72,0x2F,0xA9,0xB6,0xEF,0x1C,0x19 } }; // 9C7EF99E-8AEE-5C0D-9372-2FA9B6EF1C19
    template <> struct default_interface<winrt::WcsNativeWinUI::MainPage>{ using type = winrt::WcsNativeWinUI::IMainPage; };
    template <> struct default_interface<winrt::WcsNativeWinUI::MainWindow>{ using type = winrt::WcsNativeWinUI::IMainWindow; };
    template <> struct default_interface<winrt::WcsNativeWinUI::XamlMetaDataProvider>{ using type = winrt::Microsoft::UI::Xaml::Markup::IXamlMetadataProvider; };
    template <> struct abi<winrt::WcsNativeWinUI::IMainPage>
    {
        struct WINRT_IMPL_NOVTABLE type : inspectable_abi
        {
        };
    };
    template <> struct abi<winrt::WcsNativeWinUI::IMainWindow>
    {
        struct WINRT_IMPL_NOVTABLE type : inspectable_abi
        {
        };
    };
    template <typename D>
    struct consume_WcsNativeWinUI_IMainPage
    {
    };
    template <> struct consume<winrt::WcsNativeWinUI::IMainPage>
    {
        template <typename D> using type = consume_WcsNativeWinUI_IMainPage<D>;
    };
    template <typename D>
    struct consume_WcsNativeWinUI_IMainWindow
    {
    };
    template <> struct consume<winrt::WcsNativeWinUI::IMainWindow>
    {
        template <typename D> using type = consume_WcsNativeWinUI_IMainWindow<D>;
    };
}
#endif
