// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.221104.6

#pragma once
#ifndef WINRT_WcsNativeWinUI_1_H
#define WINRT_WcsNativeWinUI_1_H
#include "winrt/impl/WcsNativeWinUI.0.h"
WINRT_EXPORT namespace winrt::WcsNativeWinUI
{
    struct WINRT_IMPL_EMPTY_BASES IMainPage :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IMainPage>
    {
        IMainPage(std::nullptr_t = nullptr) noexcept {}
        IMainPage(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct WINRT_IMPL_EMPTY_BASES IMainWindow :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IMainWindow>
    {
        IMainWindow(std::nullptr_t = nullptr) noexcept {}
        IMainWindow(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
}
#endif
