// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.221104.6

void* winrt_make_WcsNativeWinUI_MainPage()
{
    return winrt::detach_abi(winrt::make<winrt::WcsNativeWinUI::factory_implementation::MainPage>());
}
WINRT_EXPORT namespace winrt::WcsNativeWinUI
{
    MainPage::MainPage() :
        MainPage(make<WcsNativeWinUI::implementation::MainPage>())
    {
    }
}
