
//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------
#pragma once

#include <unknwn.h>

// Undefine GetCurrentTime macro to prevent
// conflict with Storyboard::GetCurrentTime
#undef GetCurrentTime

#if __has_include(<winrt/Microsoft.UI.Xaml.h>)
#include <winrt/Microsoft.UI.Xaml.h>
#endif
#if __has_include(<winrt/Microsoft.UI.Xaml.Controls.h>)
#include <winrt/Microsoft.UI.Xaml.Controls.h>
#endif
#if __has_include(<winrt/Microsoft.UI.Xaml.Controls.Primitives.h>)
#include <winrt/Microsoft.UI.Xaml.Controls.Primitives.h>
#endif
#if __has_include(<winrt/Microsoft.UI.Xaml.Markup.h>)
#include <winrt/Microsoft.UI.Xaml.Markup.h>
#endif


namespace winrt::WcsNativeWinUI::implementation
{
    using IInspectable = ::winrt::Windows::Foundation::IInspectable;

    template <typename D, typename ... I>
    struct MainPageT : public ::winrt::WcsNativeWinUI::implementation::MainPage_base<D,
        ::winrt::Microsoft::UI::Xaml::Markup::IComponentConnector,
        I...>
    {
        using base_type = typename MainPageT::base_type;
        using base_type::base_type;
        using class_type = typename MainPageT::class_type;

        void InitializeComponent();
        virtual void Connect(int32_t connectionId, IInspectable const& target);
        virtual ::winrt::Microsoft::UI::Xaml::Markup::IComponentConnector GetBindingConnector(int32_t connectionId, IInspectable const& target);
        void UnloadObject(::winrt::Microsoft::UI::Xaml::DependencyObject const& dependencyObject);
        void DisconnectUnloadedObject(int32_t connectionId);

        ::winrt::Microsoft::UI::Xaml::Controls::Grid RootGrid()
        {
            return _RootGrid;
        }
        void RootGrid(::winrt::Microsoft::UI::Xaml::Controls::Grid value)
        {
            _RootGrid = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::Grid MainContentRoot()
        {
            return _MainContentRoot;
        }
        void MainContentRoot(::winrt::Microsoft::UI::Xaml::Controls::Grid value)
        {
            _MainContentRoot = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::Grid InitOverlay()
        {
            return _InitOverlay;
        }
        void InitOverlay(::winrt::Microsoft::UI::Xaml::Controls::Grid value)
        {
            _InitOverlay = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::TextBlock InitFooterText()
        {
            return _InitFooterText;
        }
        void InitFooterText(::winrt::Microsoft::UI::Xaml::Controls::TextBlock value)
        {
            _InitFooterText = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::ProgressBar InitProgressBar()
        {
            return _InitProgressBar;
        }
        void InitProgressBar(::winrt::Microsoft::UI::Xaml::Controls::ProgressBar value)
        {
            _InitProgressBar = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::TextBlock InitStepText()
        {
            return _InitStepText;
        }
        void InitStepText(::winrt::Microsoft::UI::Xaml::Controls::TextBlock value)
        {
            _InitStepText = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::TextBlock InitDetailText()
        {
            return _InitDetailText;
        }
        void InitDetailText(::winrt::Microsoft::UI::Xaml::Controls::TextBlock value)
        {
            _InitDetailText = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::Border InitFailurePanel()
        {
            return _InitFailurePanel;
        }
        void InitFailurePanel(::winrt::Microsoft::UI::Xaml::Controls::Border value)
        {
            _InitFailurePanel = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::TextBlock InitFailureText()
        {
            return _InitFailureText;
        }
        void InitFailureText(::winrt::Microsoft::UI::Xaml::Controls::TextBlock value)
        {
            _InitFailureText = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::TextBlock InitTipsText()
        {
            return _InitTipsText;
        }
        void InitTipsText(::winrt::Microsoft::UI::Xaml::Controls::TextBlock value)
        {
            _InitTipsText = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::Button InitRetryButton()
        {
            return _InitRetryButton;
        }
        void InitRetryButton(::winrt::Microsoft::UI::Xaml::Controls::Button value)
        {
            _InitRetryButton = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::ProgressRing InitProgressRing()
        {
            return _InitProgressRing;
        }
        void InitProgressRing(::winrt::Microsoft::UI::Xaml::Controls::ProgressRing value)
        {
            _InitProgressRing = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::TextBlock InitPercentText()
        {
            return _InitPercentText;
        }
        void InitPercentText(::winrt::Microsoft::UI::Xaml::Controls::TextBlock value)
        {
            _InitPercentText = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::TextBox LogBox()
        {
            return _LogBox;
        }
        void LogBox(::winrt::Microsoft::UI::Xaml::Controls::TextBox value)
        {
            _LogBox = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::TextBlock StatusTextBlock()
        {
            return _StatusTextBlock;
        }
        void StatusTextBlock(::winrt::Microsoft::UI::Xaml::Controls::TextBlock value)
        {
            _StatusTextBlock = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::TextBlock MetricsTextBlock()
        {
            return _MetricsTextBlock;
        }
        void MetricsTextBlock(::winrt::Microsoft::UI::Xaml::Controls::TextBlock value)
        {
            _MetricsTextBlock = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::ToggleSwitch IntraOnlyToggle()
        {
            return _IntraOnlyToggle;
        }
        void IntraOnlyToggle(::winrt::Microsoft::UI::Xaml::Controls::ToggleSwitch value)
        {
            _IntraOnlyToggle = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::ToggleSwitch AutoRotateToggle()
        {
            return _AutoRotateToggle;
        }
        void AutoRotateToggle(::winrt::Microsoft::UI::Xaml::Controls::ToggleSwitch value)
        {
            _AutoRotateToggle = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::ToggleSwitch AutoBitrateToggle()
        {
            return _AutoBitrateToggle;
        }
        void AutoBitrateToggle(::winrt::Microsoft::UI::Xaml::Controls::ToggleSwitch value)
        {
            _AutoBitrateToggle = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::ComboBox EntropyBox()
        {
            return _EntropyBox;
        }
        void EntropyBox(::winrt::Microsoft::UI::Xaml::Controls::ComboBox value)
        {
            _EntropyBox = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::ComboBox ProtocolBox()
        {
            return _ProtocolBox;
        }
        void ProtocolBox(::winrt::Microsoft::UI::Xaml::Controls::ComboBox value)
        {
            _ProtocolBox = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::ComboBox OrientationBox()
        {
            return _OrientationBox;
        }
        void OrientationBox(::winrt::Microsoft::UI::Xaml::Controls::ComboBox value)
        {
            _OrientationBox = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::TextBox MinBitrateBox()
        {
            return _MinBitrateBox;
        }
        void MinBitrateBox(::winrt::Microsoft::UI::Xaml::Controls::TextBox value)
        {
            _MinBitrateBox = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::TextBox MaxBitrateBox()
        {
            return _MaxBitrateBox;
        }
        void MaxBitrateBox(::winrt::Microsoft::UI::Xaml::Controls::TextBox value)
        {
            _MaxBitrateBox = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::ComboBox ResolutionBox()
        {
            return _ResolutionBox;
        }
        void ResolutionBox(::winrt::Microsoft::UI::Xaml::Controls::ComboBox value)
        {
            _ResolutionBox = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::TextBox FpsBox()
        {
            return _FpsBox;
        }
        void FpsBox(::winrt::Microsoft::UI::Xaml::Controls::TextBox value)
        {
            _FpsBox = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::TextBox BitrateBox()
        {
            return _BitrateBox;
        }
        void BitrateBox(::winrt::Microsoft::UI::Xaml::Controls::TextBox value)
        {
            _BitrateBox = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::ComboBox ProfileBox()
        {
            return _ProfileBox;
        }
        void ProfileBox(::winrt::Microsoft::UI::Xaml::Controls::ComboBox value)
        {
            _ProfileBox = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::TextBox HostBox()
        {
            return _HostBox;
        }
        void HostBox(::winrt::Microsoft::UI::Xaml::Controls::TextBox value)
        {
            _HostBox = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::TextBox VideoPortBox()
        {
            return _VideoPortBox;
        }
        void VideoPortBox(::winrt::Microsoft::UI::Xaml::Controls::TextBox value)
        {
            _VideoPortBox = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::TextBox ControlPortBox()
        {
            return _ControlPortBox;
        }
        void ControlPortBox(::winrt::Microsoft::UI::Xaml::Controls::TextBox value)
        {
            _ControlPortBox = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::ToggleSwitch ThemeToggle()
        {
            return _ThemeToggle;
        }
        void ThemeToggle(::winrt::Microsoft::UI::Xaml::Controls::ToggleSwitch value)
        {
            _ThemeToggle = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::Border StatusBadgeBorder()
        {
            return _StatusBadgeBorder;
        }
        void StatusBadgeBorder(::winrt::Microsoft::UI::Xaml::Controls::Border value)
        {
            _StatusBadgeBorder = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::FontIcon StatusBadgeIcon()
        {
            return _StatusBadgeIcon;
        }
        void StatusBadgeIcon(::winrt::Microsoft::UI::Xaml::Controls::FontIcon value)
        {
            _StatusBadgeIcon = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::TextBlock StatusBadgeText()
        {
            return _StatusBadgeText;
        }
        void StatusBadgeText(::winrt::Microsoft::UI::Xaml::Controls::TextBlock value)
        {
            _StatusBadgeText = value;
        }
        
    protected:
        bool _contentLoaded{false};

    private:
        struct MainPage_obj1_Bindings;

        ::winrt::Microsoft::UI::Xaml::Controls::Grid _RootGrid{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::Grid _MainContentRoot{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::Grid _InitOverlay{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::TextBlock _InitFooterText{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::ProgressBar _InitProgressBar{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::TextBlock _InitStepText{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::TextBlock _InitDetailText{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::Border _InitFailurePanel{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::TextBlock _InitFailureText{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::TextBlock _InitTipsText{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::Button _InitRetryButton{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::ProgressRing _InitProgressRing{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::TextBlock _InitPercentText{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::TextBox _LogBox{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::TextBlock _StatusTextBlock{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::TextBlock _MetricsTextBlock{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::ToggleSwitch _IntraOnlyToggle{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::ToggleSwitch _AutoRotateToggle{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::ToggleSwitch _AutoBitrateToggle{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::ComboBox _EntropyBox{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::ComboBox _ProtocolBox{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::ComboBox _OrientationBox{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::TextBox _MinBitrateBox{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::TextBox _MaxBitrateBox{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::ComboBox _ResolutionBox{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::TextBox _FpsBox{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::TextBox _BitrateBox{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::ComboBox _ProfileBox{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::TextBox _HostBox{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::TextBox _VideoPortBox{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::TextBox _ControlPortBox{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::ToggleSwitch _ThemeToggle{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::Border _StatusBadgeBorder{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::FontIcon _StatusBadgeIcon{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::TextBlock _StatusBadgeText{nullptr};
    };
}

