// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.221104.6

void* winrt_make_WcsNativeWinUI_XamlMetaDataProvider()
{
    return winrt::detach_abi(winrt::make<winrt::WcsNativeWinUI::factory_implementation::XamlMetaDataProvider>());
}
WINRT_EXPORT namespace winrt::WcsNativeWinUI
{
    XamlMetaDataProvider::XamlMetaDataProvider() :
        XamlMetaDataProvider(make<WcsNativeWinUI::implementation::XamlMetaDataProvider>())
    {
    }
}
