// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.221104.6

#pragma once
#ifndef WINRT_WcsNativeWinUI_H
#define WINRT_WcsNativeWinUI_H
#include "winrt/base.h"
static_assert(winrt::check_version(CPPWINRT_VERSION, "2.0.221104.6"), "Mismatched C++/WinRT headers.");
#define CPPWINRT_VERSION "2.0.221104.6"
#include "winrt/impl/Microsoft.UI.Composition.2.h"
#include "winrt/impl/Microsoft.UI.Xaml.2.h"
#include "winrt/impl/Microsoft.UI.Xaml.Controls.2.h"
#include "winrt/impl/Microsoft.UI.Xaml.Markup.2.h"
#include "winrt/impl/WcsNativeWinUI.2.h"
namespace winrt::impl
{
    template <typename D>
    struct produce<D, winrt::WcsNativeWinUI::IMainPage> : produce_base<D, winrt::WcsNativeWinUI::IMainPage>
    {
    };
    template <typename D>
    struct produce<D, winrt::WcsNativeWinUI::IMainWindow> : produce_base<D, winrt::WcsNativeWinUI::IMainWindow>
    {
    };
}
WINRT_EXPORT namespace winrt::WcsNativeWinUI
{
}
namespace std
{
#ifndef WINRT_LEAN_AND_MEAN
    template<> struct hash<winrt::WcsNativeWinUI::IMainPage> : winrt::impl::hash_base {};
    template<> struct hash<winrt::WcsNativeWinUI::IMainWindow> : winrt::impl::hash_base {};
    template<> struct hash<winrt::WcsNativeWinUI::MainPage> : winrt::impl::hash_base {};
    template<> struct hash<winrt::WcsNativeWinUI::MainWindow> : winrt::impl::hash_base {};
    template<> struct hash<winrt::WcsNativeWinUI::XamlMetaDataProvider> : winrt::impl::hash_base {};
#endif
#ifdef __cpp_lib_format
#endif
}
#endif
